name: 'Xcode Cache'
description: 'Cache Xcode''s DerivedData for incremental build.'
author: 'irgaly'
branding:
  icon: 'zap'
  color: 'blue'
inputs:
  key:
    description: 'cache key for DerivedData'
    required: true
  restore-keys:
    description: 'cache restore keys for DerivedData. example: '
    required: false
    default: ''
  deriveddata-directory:
    description: 'a directory of project''s DerivedData. default: ~/Library/Developer/Xcode/DerivedData'
    required: false
    default: ''
  sourcepackages-directory:
    description: 'a directory of SourcePackages. default: ${deriveddata-directory}/SourcePackages'
    required: false
    default: ''
  restore-mtime-targets:
    description: 'the targets glob pattern of restoring mtime. exclude pattern ''!{pattern}'' can be used.'
    required: false
    default: ''
  swiftpm-package-resolved-file:
    description: 'Xcode''s Package.resolved file path glob pattern. default: **/*.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved , **/*.xcworkspace/xcshareddata/swiftpm/Package.resolved'
    required: false
    default: ''
  swiftpm-cache-key:
    description: 'cache key for SourcePackages. default: irgaly/xcode-cache-sourcepackages-${{ hashFiles({resolvedFiles}) }}'
    required: false
    default: ''
  swiftpm-cache-restore-keys:
    description: 'cache restore keys for SourcePackages'
    required: false
    default: ''
  use-default-mtime-targets:
    description: 'process default mtime targets: **/*.swift , **/*.xib , **/*.storyboard , **/*.strings , **/*.plist , **/*.bundle , **/*.bundle/**/* , **/*.m , **/*.mm , **/*.h , **/*.c , **/*.cc , **/*.cpp , **/*.hpp , **/*.hxx'
    required: false
    default: 'true'
  verbose:
    description: 'enable verbose logging'
    required: false
    default: 'false'
runs:
  using: 'node20'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
  post-if: success()
