name: Build distributions & commit dist

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-dist:
    runs-on: macos-latest
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && !github.event.pull_request.draft) }}
    steps:
      - uses: actions/checkout@v3
        if: github.event_name == 'push'
      - uses: actions/checkout@v3
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v3
        with:
          cache: npm
      - run: npm install
      - shell: bash -xeu {0}
        run: npm run build
      - uses: crazy-max/ghaction-import-gpg@v6
        id: gpg
        with:
          gpg_private_key: ${{ secrets.SIGNING_PGP_KEY }}
          passphrase: ${{ secrets.SIGNING_PGP_PASSWORD }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Commit changes
        env:
          GIT_AUTHOR_NAME: irgaly
          GIT_AUTHOR_EMAIL: ${{ steps.gpg.outputs.email }}
          GIT_COMMITTER_NAME: irgaly
          GIT_COMMITTER_EMAIL: ${{ steps.gpg.outputs.email }}
        shell: bash +e {0}
        run: |
          git commit -am "Update dist" && git push origin HEAD
          exit 0
